### ISSUE TITLE
environment vars

### ISSUE THREAD

**Issue by jobyid** [deta/cloud-docs#126]
Hey guys is there a way I can set Environment values in my Deta Micro so that may app can connect to other API and so I don't hard code the API keys into the code?

**Comment by abdelhai** [comment]
@jobyid Use the [update command](https://docs.deta.sh/docs/cli/commands/#deta-update). Example: `deta update -e .env`. Put your env vars in the `.env`

Feel free to use Slack, Intercom or email to get a faster response.

**Comment by lakuapik** [comment]
@abdelhai @jobyid let me share my current alternative i use.

first of all, i never knew the command exists.

so instead, i use dotenv loader package

with python i use https://pypi.org/project/python-dotenv 
or javascript i use https://www.npmjs.com/package/dotenv

as you may know, those package function is to set environment variable from a file, usually `.env` file.
but  in my experience the `.env` file will be ignored when you deploy your deta app.
my current solution is to store env to other file and then load it with extra configuration.
with that i do not need to update with the command above when i made env changes, just re-deploy it.

**Comment by abdelhai** [comment]
We don't upload the .env file because developers store secrets there, and it could lead to security issues. The official way to set env vars is by using the `update` command as in: `deta update -e .env`

Env vars are encrypted, source code is not. Please make sure you use the appropriate command to ensure security.
@lakuapik

**Comment by lakuapik** [comment]
@abdelhai thanks for the advice, as you see, we developers maybe doesnt know the command exists. maybe this kind of information should be in docs?

**Comment by abdelhai** [comment]
@abdelhai  Thanks for the feedback, added: https://docs.deta.sh/docs/micros/env

**Comment by abdelhai** [comment]
@lakuapik  Thanks for the feedback, added: https://docs.deta.sh/docs/micros/env
