### ISSUE TITLE
Python 3.9 runtime is not supported

### ISSUE THREAD

**Issue by mehdinourollah** [deta/cloud-docs#143]
I have changed the **.deta/prog_info** file python runtime version to **3.9** 
![image](https://user-images.githubusercontent.com/5097056/126778859-da4a1f0f-bc39-4093-b5fc-4664304a8666.png)
but when I use `deta pull` it says runtime not supported
![image](https://user-images.githubusercontent.com/5097056/126778930-e27c1153-8269-4e9d-a574-e0a2e95e22a7.png)

I need to use that runtime for my FastAPI micro app.

**Comment by abdelhai** [comment]
Hi @mehdinourollah, the contents of `.deta/prog_info` are not meant to be changed by the user.
As [per our docs](https://docs.deta.sh/docs/micros/about#technical-specifications), at the moment only Python 3.7 is supported.
