### ISSUE TITLE
Pinging the Website

### ISSUE THREAD

**Issue by Hunter2809** [deta/cloud-docs#152]
Hey there! 

I am hosting an API on your service (your service is epic), and I want to track the uptime of the API. Will it be fine if I ping the url using uptimerobot every 10 min as I am tryna host a discord bot on it (not a big one, but a private one for one server only) ? Or is there a way to increase the sleep time of the website as it sleeps as soon as I exit the website... 

Thanks!

**Comment by abdelhai** [comment]
@Hunter2807 thanks for opening this issue and sorry for the late response.
Hosting Discord bots is not really supported.
It is fine if you ping you Micro regularly though if that works for you.
