### ISSUE TITLE
Issue In Form Endpoints Section

### ISSUE THREAD

**Issue by Sam-Varghese** [deta/cloud-docs#157]
Hello sir, firstly thankyou so much for Deta

I am a newbie to Deta, and thought to start with [Form Endpoints](https://docs.deta.sh/docs/tutorials/form-endpoints-guide). I executed all the commands successfully till `npm install express`, but got an error while executing `deta new` command. Here are the commands that I executed sequentially:

```none
mkdir express-form
cd express-form
npm install express
deta new
```

But got the following message while trying to execute `deta new` command

`No entrypoint file found in 'D:\VS Code Workspace\Rough Space\express-form'. Please, provide a name or path to create a new micro elsewhere. See deta new --help.'`

Let me also attach screenshots so that you could understand my issue better

![image](https://user-images.githubusercontent.com/79152648/129687037-04b65f53-2401-4701-af74-3c620161f8b4.png)

I know I might be making some silly mistake or something, but can't understand why even though I am following all the steps you mentioned sequentially, I am not getting the desired output.

In case you require information of my system, then here is it:

```none
OS Name	Microsoft Windows 11 Home Single Language
Version	10.0.22000 Build 22000
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	SAMS-LAPTOP
System Manufacturer	HP
System Model	HP Pavilion Laptop 15-eg0xxx
System Type	x64-based PC
System SKU	2N1K7PA#ACJ
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz, 2419 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Insyde F.12, 17-03-2021
SMBIOS Version	3.3
Embedded Controller Version	34.27
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	8850
BaseBoard Version	34.27
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22000.1"
User Name	SAMS-LAPTOP\Hp
Time Zone	India Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.8 GB
Available Physical Memory	6.89 GB
Total Virtual Memory	18.1 GB
Available Virtual Memory	3.93 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

```

Could you kindly help me to get started with Deta

ThankYou
Sam Varghese

**Comment by abdelhai** [comment]
@Sam-Varghese You need to create an `index.js` file first (step 2). Please read the docs very carefully :)

**Comment by Sam-Varghese** [comment]
Oh nooooooooo 🤦‍♂️🤦‍♂️Very sorry to disturb you. My mistake. I am terrible at reading docs. ThankYou very much for helping. Can't tell for how long I was stuck on this issue, and in the end gathered the courage to raise an issue.

![OhNoGIF](https://user-images.githubusercontent.com/79152648/129774172-fac3fd62-6ed2-4007-9516-9a6db33f90c6.gif)

**Comment by abdelhai** [comment]
@Sam-Varghese All good, it happens. Feel free to message us on Intercom via the website for faster help. Cheers!
