### ISSUE TITLE
Error: invalid character 'H' looking for beginning of value

### ISSUE THREAD

**Issue by calpa** [deta/cloud-docs#58]
To produce this bug, just follow the doc in the [website](https://docs.deta.sh/docs/micros/run).

When I run the command `deta run`, the response returns error:

```
Running micro...

Response:
Error: invalid character 'H' looking for beginning of value
```

index.js file is:

```
const { app } = require('deta');

app.lib.run((event) => {
  return {
    message: event.json,
  };
});

module.exports = app;
```

nvm version: 0.34.0
node version: v13.8.0
npm version: 7.0.2

**Comment by xeust** [comment]
Hi,

I can't seem to replicate the issue on my end.

Would you mind sharing the version of your cli by running:

`deta version`

If the version is not `deta v1.1.2-beta x86_64-darwin` could you try running `deta version upgrade` and then `deta run` again?

**Comment by calpa** [comment]
Cannot reproduce this error
