### ISSUE TITLE
Misnamed method call in Python example

### ISSUE THREAD

**Issue by jtbaker** [deta/cloud-docs#64]
While getting started setting up my account, I noticed a typo in one of the python examples in the user admin portal. After looking through the docs, the method call for creating a new record should be `users.insert()` instead of `users.add()`. I searched through the repos under this organization and couldn't locate where this reference comes from to try and make a PR to fix, but thought I should let you know.

![image](https://user-images.githubusercontent.com/25542515/98406937-6c29d080-2034-11eb-8416-4f8c7f6e5cdb.png)

**Comment by abdelhai** [comment]
Hi @jtbaker thanks for pointing this out – apology for the inconvenience. Fix is on the way.

**Comment by xeust** [comment]
The fix for this should be live -- thanks for the heads up!
